---

- hosts: "{{ hosts }}"
  become: true
  vars:
    debian_package_tar: "ApacheDebian.tar.gz"
    debian_package_path: "/tmp/apache_debian/"
    apache_port: "80"
  #specify ip hostname TARGET should be box name from inventory file
    target_ip: "{{ lookup('inventory_hostnames', 'TARGET') }}"
  tasks:

    - name: Copy install_apache_ubuntu.sh to remote server
      copy:
        src: "install_apache_ubuntu.sh"
        dest: "/tmp/"

    - name: Make script executable
      shell: 'chmod +x /tmp/install_apache_ubuntu.sh'
 
    - name: Running Apache installation shell script
      shell: "/tmp/install_apache_ubuntu.sh {{ debian_package_tar }} {{ debian_package_path }} {{ apache_port }} {{ target_ip }}"
      ignore_errors: yes
      tags:
        - install_apache_as_service
