---

- hosts: "{{ hosts }}"
  become: yes
  vars:
    software_source: "/tmp/Apache"
    assets_dir: "/tmp"
    httpd_rpm: "httpd_rpm"
  tasks:

#  - name: Define a repository
#    shell: 'sudo createrepo "{{ assets_dir }}/{{ httpd_rpm }}"'

#  - name: Create a repository
#    yum_repository:
#      name: httpd
#      description: "This is local repository to install httpd"
#      baseurl: file://{{ assets_dir }}/{{ httpd_rpm }}
#      gpgcheck: no
#      enabled: 1
#      state: present

#  - name: Install the packages
#    command: 'sudo yum install -y httpd'
#    ignore_errors: yes
    - name: Copy install_apache.sh to remote server
      copy:
        src: "install_apache.sh"
        dest: "/tmp/"

    - name: Make script executable
      shell: 'sudo chmod +x /tmp/install_apache.sh'

    - name: Running Apache installation shell script
      shell: "sudo /tmp/install_apache.sh {{ assets_dir }}/{{ httpd_rpm }} httpd"
      tags:
        - install_apache_as_service
